pre_bump_hooks = [
    "poetry version {{version}}"
]

post_bump_hooks = [
    "git push",
    "git push origin {{version}}",
]

[changelog]
authors = [{ signature = "Roman Kurakin", username = "romankurakin" }]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "data-structures-and-algorithms"
owner = "romankurakin"
